# Generated by Django 4.2.9 on 2025-04-28 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=100)),
                ('sentences', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
