# Generated by Django 4.2.9 on 2025-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_userspeech_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspeech',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='userspeech',
            name='sentences',
        ),
        migrations.RemoveField(
            model_name='userspeech',
            name='website',
        ),
        migrations.AddField(
            model_name='userspeech',
            name='speech',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='speech_embedding',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userspeech',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
