# Generated by Django 4.2.9 on 2025-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_remove_userspeech_embedding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspeech',
            old_name='speech_embedding',
            new_name='embedding',
        ),
        migrations.RemoveField(
            model_name='userspeech',
            name='speech',
        ),
        migrations.AddField(
            model_name='userspeech',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
    ]
