# Generated by Django 4.2.9 on 2025-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_userhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=20, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_text', models.TextField()),
            ],
        ),
    ]
