# Generated by Django 4.2.9 on 2025-04-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0006_sensitiveentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.sensitiveentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.userspeech')),
            ],
            options={
                'unique_together': {('user', 'entity')},
            },
        ),
    ]
