# Generated by Django 4.2.9 on 2025-04-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0007_userentityrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_ids', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matcher.userspeech')),
            ],
        ),
        migrations.DeleteModel(
            name='UserEntityRelation',
        ),
    ]
